export const noteActionTypes = {
  SET_NOTES: "SET_NOTES",
  REMOVE_NOTE: "REMOVE_NOTE",
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL"
};
